export const JOB_GEO_VALUES = [
    "apac",
    "emea",
    "latam",
    "argentina",
    "australia",
    "austria",
    "belgium",
    "brazil",
    "bulgaria",
    "canada",
    "china",
    "hong-kong",
    "costa-rica",
    "croatia",
    "cyprus",
    "czechia",
    "denmark",
    "estonia",
    "europe",
    "finland",
    "france",
    "germany",
    "greece",
    "hungary",
    "ireland",
    "israel",
    "italy",
    "japan",
    "latvia",
    "lithuania",
    "mexico",
    "netherlands",
    "new-zealand",
    "norway",
    "philippines",
    "poland",
    "portugal",
    "romania",
    "serbia",
    "singapore",
    "slovakia",
    "slovenia",
    "south-korea",
    "spain",
    "sweden",
    "switzerland",
    "thailand",
    "turkiye",
    "united-arab-emirates",
    "uk",
    "ukraine",
    "usa",
    "vietnam",
] as const;

export const INDUSTRY_VALUES = [
    "business",
    "copywriting",
    "healthcare",
    "education",
    "admin-support",
    "supporting",
    "data-science",
    "design-multimedia",
    "admin",
    "accounting-finance",
    "hr",
    "marketing",
    "management",
    "dev",
    "seller",
    "seo",
    "smm",
    "engineering",
    "technical-support",
    "web-app-design",
] as const;

export type JobGeo = (typeof JOB_GEO_VALUES)[number];
export type Industry = (typeof INDUSTRY_VALUES)[number];

export const JOB_GEO_LABELS: Record<JobGeo, string> = {
    apac: "APAC",
    emea: "EMEA",
    latam: "LATAM",
    argentina: "Argentina",
    australia: "Australia",
    austria: "Austria",
    belgium: "Belgium",
    brazil: "Brazil",
    bulgaria: "Bulgaria",
    canada: "Canada",
    china: "China",
    "hong-kong": "Hong Kong",
    "costa-rica": "Costa Rica",
    croatia: "Croatia",
    cyprus: "Cyprus",
    czechia: "Czechia",
    denmark: "Denmark",
    estonia: "Estonia",
    europe: "Europe",
    finland: "Finland",
    france: "France",
    germany: "Germany",
    greece: "Greece",
    hungary: "Hungary",
    ireland: "Ireland",
    israel: "Israel",
    italy: "Italy",
    japan: "Japan",
    latvia: "Latvia",
    lithuania: "Lithuania",
    mexico: "Mexico",
    netherlands: "Netherlands",
    "new-zealand": "New Zealand",
    norway: "Norway",
    philippines: "Philippines",
    poland: "Poland",
    portugal: "Portugal",
    romania: "Romania",
    serbia: "Serbia",
    singapore: "Singapore",
    slovakia: "Slovakia",
    slovenia: "Slovenia",
    "south-korea": "South Korea",
    spain: "Spain",
    sweden: "Sweden",
    switzerland: "Switzerland",
    thailand: "Thailand",
    turkiye: "Türkiye",
    "united-arab-emirates": "United Arab Emirates",
    uk: "United Kingdom",
    ukraine: "Ukraine",
    usa: "United States",
    vietnam: "Vietnam",
};

export const INDUSTRY_LABELS: Record<Industry, string> = {
    business: "Business",
    copywriting: "Copywriting",
    healthcare: "Healthcare",
    education: "Education",
    "admin-support": "Admin Support",
    supporting: "Customer Support",
    "data-science": "Data Science",
    "design-multimedia": "Design & Multimedia",
    admin: "Administration",
    "accounting-finance": "Accounting & Finance",
    hr: "HR & Recruiting",
    marketing: "Marketing",
    management: "Management",
    dev: "Software Development",
    seller: "Sales",
    seo: "SEO",
    smm: "Social Media",
    engineering: "Engineering",
    "technical-support": "Technical Support",
    "web-app-design": "Web & App Design",
};
